const elements = [
    { atomicNumber: 1, symbol: "H", name: "Hydrogen", info: "Lightest and most abundant element in the universe.", uses: "Fuel, ammonia production, fuel cells.", countries: "Global, especially in water." },
    { atomicNumber: 2, symbol: "He", name: "Helium", info: "A noble gas with low density, used in balloons and cooling.", uses: "Balloons, cooling, scientific research.", countries: "USA, Qatar." },
    { atomicNumber: 3, symbol: "Li", name: "Lithium", info: "A soft, silvery metal, used in rechargeable batteries.", uses: "Batteries, glass, ceramics.", countries: "Australia, Chile, China." },
    { atomicNumber: 4, symbol: "Be", name: "Beryllium", info: "A hard, gray metal used in aerospace materials.", uses: "Aerospace, X-ray windows.", countries: "USA, China." },
    { atomicNumber: 5, symbol: "B", name: "Boron", info: "A metalloid used in glass and detergents.", uses: "Glass, ceramics, detergents.", countries: "Turkey, USA." },
    { atomicNumber: 6, symbol: "C", name: "Carbon", info: "The basis for all known life, found in many compounds.", uses: "Steel, fuels, plastics.", countries: "Global." },
    { atomicNumber: 7, symbol: "N", name: "Nitrogen", info: "A colorless gas making up 78% of Earth's atmosphere.", uses: "Fertilizers, explosives, refrigeration.", countries: "Global." },
    { atomicNumber: 8, symbol: "O", name: "Oxygen", info: "Essential for respiration, used in various industries.", uses: "Steel production, medical oxygen.", countries: "Global." },
    { atomicNumber: 9, symbol: "F", name: "Fluorine", info: "A highly reactive pale yellow gas.", uses: "Toothpaste, refrigerants.", countries: "USA, China." },
    { atomicNumber: 10, symbol: "Ne", name: "Neon", info: "A noble gas used in neon signs.", uses: "Neon signs, cryogenics.", countries: "Russia, USA." },
    { atomicNumber: 11, symbol: "Na", name: "Sodium", info: "A soft, reactive metal used in salt.", uses: "Salt, soap, glass.", countries: "Global." },
    { atomicNumber: 12, symbol: "Mg", name: "Magnesium", info: "A lightweight metal used in alloys.", uses: "Alloys, fireworks, medicine.", countries: "China, Russia." },
    { atomicNumber: 13, symbol: "Al", name: "Aluminum", info: "A lightweight, corrosion-resistant metal.", uses: "Cans, foil, construction.", countries: "China, Russia, Canada." },
    { atomicNumber: 14, symbol: "Si", name: "Silicon", info: "A metalloid used in electronics and glass.", uses: "Electronics, glass, solar cells.", countries: "China, USA." },
    { atomicNumber: 15, symbol: "P", name: "Phosphorus", info: "A reactive non-metal essential for life.", uses: "Fertilizers, detergents.", countries: "China, USA." },
    { atomicNumber: 16, symbol: "S", name: "Sulfur", info: "A yellow non-metal used in fertilizers and matches.", uses: "Fertilizers, rubber, gunpowder.", countries: "China, USA, Canada." },
    { atomicNumber: 17, symbol: "Cl", name: "Chlorine", info: "A yellow-green gas used for water disinfection.", uses: "Disinfection, PVC production.", countries: "USA, Canada." },
    { atomicNumber: 18, symbol: "Ar", name: "Argon", info: "A noble gas used in welding and lighting.", uses: "Welding, lighting, scientific research.", countries: "Global." },
    { atomicNumber: 19, symbol: "K", name: "Potassium", info: "A soft, reactive metal essential for plant growth.", uses: "Fertilizers, fireworks.", countries: "Canada, Russia." },
    { atomicNumber: 20, symbol: "Ca", name: "Calcium", info: "An alkaline earth metal essential for bones.", uses: "Cement, glass, dietary supplements.", countries: "China, USA." },
    { atomicNumber: 21, symbol: "Sc", name: "Scandium", info: "A rare earth metal used in aerospace components.", uses: "Aerospace, sports equipment.", countries: "China, Russia." },
    { atomicNumber: 22, symbol: "Ti", name: "Titanium", info: "A strong, lightweight metal.", uses: "Aircraft, medical implants.", countries: "China, Russia." },
    { atomicNumber: 23, symbol: "V", name: "Vanadium", info: "A metal used to strengthen steel.", uses: "Steel alloys, batteries.", countries: "China, Russia." },
    { atomicNumber: 24, symbol: "Cr", name: "Chromium", info: "A shiny, corrosion-resistant metal.", uses: "Stainless steel, pigments.", countries: "South Africa, Kazakhstan." },
    { atomicNumber: 25, symbol: "Mn", name: "Manganese", info: "A metal used in steel production.", uses: "Steel production, batteries.", countries: "South Africa, Australia." },
    { atomicNumber: 26, symbol: "Fe", name: "Iron", info: "A common metal used in construction.", uses: "Steel, magnets, machinery.", countries: "Australia, Brazil." },
    { atomicNumber: 27, symbol: "Co", name: "Cobalt", info: "A metal used in batteries and alloys.", uses: "Batteries, magnets, pigments.", countries: "DR Congo, Canada." },
    { atomicNumber: 28, symbol: "Ni", name: "Nickel", info: "A corrosion-resistant metal.", uses: "Alloys, coins, batteries.", countries: "Indonesia, Philippines." },
    { atomicNumber: 29, symbol: "Cu", name: "Copper", info: "A highly conductive metal.", uses: "Wiring, plumbing, coins.", countries: "Chile, Peru, China." },
    { atomicNumber: 30, symbol: "Zn", name: "Zinc", info: "A metal used in galvanization and alloys.", uses: "Galvanization, alloys, batteries.", countries: "China, Australia." },
    { atomicNumber: 31, symbol: "Ga", name: "Gallium", info: "A metal that melts at low temperatures.", uses: "Electronics, solar panels.", countries: "China, Germany." },
    { atomicNumber: 32, symbol: "Ge", name: "Germanium", info: "A metalloid used in electronics.", uses: "Electronics, fiber optics.", countries: "China, Russia." },
    { atomicNumber: 33, symbol: "As", name: "Arsenic", info: "A toxic metalloid.", uses: "Pesticides, semiconductors.", countries: "China, Russia." },
    { atomicNumber: 34, symbol: "Se", name: "Selenium", info: "A non-metal used in electronics.", uses: "Electronics, glass production.", countries: "China, USA." },
    { atomicNumber: 35, symbol: "Br", name: "Bromine", info: "A reddish-brown liquid used in flame retardants.", uses: "Flame retardants, agriculture.", countries: "China, Israel." },
    { atomicNumber: 36, symbol: "Kr", name: "Krypton", info: "A noble gas used in lighting.", uses: "Lighting, photography.", countries: "Global." },

        { atomicNumber: 37, symbol: "Rb", name: "Rubidium", info: "A soft, highly reactive metal.", uses: "Research, atomic clocks.", countries: "USA, Russia." },
        { atomicNumber: 38, symbol: "Sr", name: "Strontium", info: "A soft metal that ignites in air.", uses: "Fireworks, metal alloys.", countries: "China, Mexico." },
        { atomicNumber: 39, symbol: "Y", name: "Yttrium", info: "A rare earth element used in electronics.", uses: "Lasers, phosphors.", countries: "China, India." },
        { atomicNumber: 40, symbol: "Zr", name: "Zirconium", info: "A corrosion-resistant metal.", uses: "Nuclear reactors, ceramics.", countries: "Australia, South Africa." },
        { atomicNumber: 41, symbol: "Nb", name: "Niobium", info: "A soft metal used in steel alloys.", uses: "Steel production, superconductors.", countries: "Brazil, Canada." },
        { atomicNumber: 42, symbol: "Mo", name: "Molybdenum", info: "A hard metal used in alloys.", uses: "Steel alloys, electronics.", countries: "China, USA." },
        { atomicNumber: 43, symbol: "Tc", name: "Technetium", info: "A radioactive metal used in medicine.", uses: "Medical imaging.", countries: "Synthetic." },
        { atomicNumber: 44, symbol: "Ru", name: "Ruthenium", info: "A rare transition metal.", uses: "Electronics, catalysts.", countries: "Russia, Canada." },
        { atomicNumber: 45, symbol: "Rh", name: "Rhodium", info: "A rare, reflective metal.", uses: "Catalysts, jewelry.", countries: "South Africa, Russia." },
        { atomicNumber: 46, symbol: "Pd", name: "Palladium", info: "A rare metal used in electronics.", uses: "Catalysts, electronics.", countries: "Russia, South Africa." },
        { atomicNumber: 47, symbol: "Ag", name: "Silver", info: "A precious metal with high conductivity.", uses: "Jewelry, electronics, coins.", countries: "Mexico, Peru." },
        { atomicNumber: 48, symbol: "Cd", name: "Cadmium", info: "A toxic metal used in batteries.", uses: "Batteries, pigments.", countries: "China, Japan." },
        { atomicNumber: 49, symbol: "In", name: "Indium", info: "A soft metal used in electronics.", uses: "Touch screens, alloys.", countries: "China, Canada." },
        { atomicNumber: 50, symbol: "Sn", name: "Tin", info: "A corrosion-resistant metal.", uses: "Solder, alloys, coatings.", countries: "China, Indonesia." },
        { atomicNumber: 51, symbol: "Sb", name: "Antimony", info: "A metalloid used in fire retardants.", uses: "Batteries, flame retardants.", countries: "China, Russia." },
        { atomicNumber: 52, symbol: "Te", name: "Tellurium", info: "A rare metalloid used in electronics.", uses: "Solar cells, alloys.", countries: "China, Japan." },
        { atomicNumber: 53, symbol: "I", name: "Iodine", info: "A halogen essential for health.", uses: "Medicine, photography.", countries: "Chile, Japan." },
        { atomicNumber: 54, symbol: "Xe", name: "Xenon", info: "A noble gas used in lighting.", uses: "Lighting, anesthesia.", countries: "Russia, USA." },
        { atomicNumber: 55, symbol: "Cs", name: "Cesium", info: "A soft, highly reactive metal.", uses: "Atomic clocks, electronics.", countries: "Canada, USA." },
        { atomicNumber: 56, symbol: "Ba", name: "Barium", info: "A metal used in drilling fluids.", uses: "Drilling, glassmaking.", countries: "China, India." },
        { atomicNumber: 57, symbol: "La", name: "Lanthanum", info: "A soft, ductile metal.", uses: "Batteries, catalysts.", countries: "China, USA." },
        // Elements 58 through 71 (Lanthanoids) continue here
        { atomicNumber: 58, symbol: "Ce", name: "Cerium", info: "A rare earth metal used in catalysts.", uses: "Glass polishing, catalysts.", countries: "China, USA." },
        { atomicNumber: 59, symbol: "Pr", name: "Praseodymium", info: "A soft, silvery metal.", uses: "Magnets, glass colorant.", countries: "China, USA." },
        { atomicNumber: 60, symbol: "Nd", name: "Neodymium", info: "A magnetic metal used in electronics.", uses: "Magnets, lasers.", countries: "China, USA." },
        { atomicNumber: 61, symbol: "Pm", name: "Promethium", info: "A radioactive element.", uses: "Batteries, scientific research.", countries: "Synthetic." },
        { atomicNumber: 62, symbol: "Sm", name: "Samarium", info: "A metal used in magnets.", uses: "Magnets, nuclear reactors.", countries: "China, USA." },
        { atomicNumber: 63, symbol: "Eu", name: "Europium", info: "A rare earth metal used in phosphorescent materials.", uses: "TV screens, fluorescent lights.", countries: "China, USA." },
        { atomicNumber: 64, symbol: "Gd", name: "Gadolinium", info: "A metal used in MRI contrast agents.", uses: "MRI, magnets.", countries: "China, USA." },
        { atomicNumber: 65, symbol: "Tb", name: "Terbium", info: "A rare earth metal used in electronics.", uses: "Magnets, lighting.", countries: "China, USA." },
        { atomicNumber: 66, symbol: "Dy", name: "Dysprosium", info: "A metal used in magnets and lasers.", uses: "Magnets, lasers.", countries: "China, USA." },
        { atomicNumber: 67, symbol: "Ho", name: "Holmium", info: "A rare metal used in magnets.", uses: "Magnets, nuclear control rods.", countries: "China, USA." },
        { atomicNumber: 68, symbol: "Er", name: "Erbium", info: "A metal used in fiber optics.", uses: "Fiber optics, lasers.", countries: "China, USA." },
        { atomicNumber: 69, symbol: "Tm", name: "Thulium", info: "A rare metal used in X-rays.", uses: "X-ray devices, lasers.", countries: "China, USA." },
        { atomicNumber: 70, symbol: "Yb", name: "Ytterbium", info: "A rare earth element used in electronics.", uses: "Lasers, atomic clocks.", countries: "China, USA." },
        { atomicNumber: 71, symbol: "Lu", name: "Lutetium", info: "A rare earth metal.", uses: "PET scanners, research.", countries: "China, USA." },
        { atomicNumber: 72, symbol: "Hf", name: "Hafnium", info: "A metal used in nuclear reactors.", uses: "Nuclear reactors, electronics.", countries: "China, South Africa." },
        { atomicNumber: 73, symbol: "Ta", name: "Tantalum", info: "A metal used in electronics.", uses: "Capacitors, medical implants.", countries: "Rwanda, Brazil." },
        { atomicNumber: 74, symbol: "W", name: "Tungsten", info: "A hard metal with a high melting point.", uses: "Filaments, tools.", countries: "China, Russia." },
        { atomicNumber: 75, symbol: "Re", name: "Rhenium", info: "A rare metal used in jet engines.", uses: "Jet engines, catalysts.", countries: "Chile, USA." },
        { atomicNumber: 76, symbol: "Os", name: "Osmium", info: "A hard, dense metal.", uses: "Alloys, pen tips.", countries: "Russia, South Africa." },
        { atomicNumber: 77, symbol: "Ir", name: "Iridium", info: "A very dense metal.", uses: "Electronics, spark plugs.", countries: "South Africa, Russia." },
        { atomicNumber: 78, symbol: "Pt", name: "Platinum", info: "A precious metal used in jewelry.", uses: "Jewelry, catalytic converters.", countries: "South Africa, Russia." },


            { atomicNumber: 79, symbol: "Au", name: "Gold", info: "A precious metal valued for its conductivity and beauty.", uses: "Jewelry, electronics, currency.", countries: "South Africa, Australia." },
            { atomicNumber: 80, symbol: "Hg", name: "Mercury", info: "A liquid metal at room temperature.", uses: "Thermometers, dental amalgams.", countries: "China, Kyrgyzstan." },
            { atomicNumber: 81, symbol: "Tl", name: "Thallium", info: "A soft, toxic metal.", uses: "Electronics, medicine.", countries: "China, USA." },
            { atomicNumber: 82, symbol: "Pb", name: "Lead", info: "A soft, malleable heavy metal.", uses: "Batteries, shielding.", countries: "China, Australia." },
            { atomicNumber: 83, symbol: "Bi", name: "Bismuth", info: "A brittle metal with low toxicity.", uses: "Medicines, alloys.", countries: "China, Bolivia." },
            { atomicNumber: 84, symbol: "Po", name: "Polonium", info: "A rare and highly radioactive element.", uses: "Anti-static devices, nuclear research.", countries: "Synthetic." },
            { atomicNumber: 85, symbol: "At", name: "Astatine", info: "A rare and radioactive halogen.", uses: "Cancer treatment research.", countries: "Synthetic." },
            { atomicNumber: 86, symbol: "Rn", name: "Radon", info: "A radioactive noble gas.", uses: "Cancer treatment, research.", countries: "Naturally occurring." },
            { atomicNumber: 87, symbol: "Fr", name: "Francium", info: "An extremely rare and highly radioactive metal.", uses: "Scientific research.", countries: "Synthetic." },
            { atomicNumber: 88, symbol: "Ra", name: "Radium", info: "A radioactive metal formerly used in luminescent paints.", uses: "Cancer treatment.", countries: "Synthetic." },
            { atomicNumber: 89, symbol: "Ac", name: "Actinium", info: "A rare, radioactive metal.", uses: "Cancer treatment research.", countries: "Synthetic." },
            { atomicNumber: 90, symbol: "Th", name: "Thorium", info: "A slightly radioactive metal.", uses: "Nuclear reactors, glassmaking.", countries: "USA, India." },
            { atomicNumber: 91, symbol: "Pa", name: "Protactinium", info: "A rare, radioactive element.", uses: "Scientific research.", countries: "Synthetic." },
            { atomicNumber: 92, symbol: "U", name: "Uranium", info: "A heavy metal used as fuel in nuclear reactors.", uses: "Nuclear power, weapons.", countries: "Australia, Canada." },
            { atomicNumber: 93, symbol: "Np", name: "Neptunium", info: "A radioactive metal found in nuclear waste.", uses: "Scientific research.", countries: "Synthetic." },
            { atomicNumber: 94, symbol: "Pu", name: "Plutonium", info: "A radioactive element used in nuclear weapons.", uses: "Nuclear weapons, reactors.", countries: "USA, Russia." },
            { atomicNumber: 95, symbol: "Am", name: "Americium", info: "A synthetic element used in smoke detectors.", uses: "Smoke detectors.", countries: "Synthetic." },
            { atomicNumber: 96, symbol: "Cm", name: "Curium", info: "A synthetic radioactive element.", uses: "Research.", countries: "Synthetic." },
            { atomicNumber: 97, symbol: "Bk", name: "Berkelium", info: "A synthetic radioactive metal.", uses: "Scientific research.", countries: "Synthetic." },
            { atomicNumber: 98, symbol: "Cf", name: "Californium", info: "A radioactive metal used in cancer treatment.", uses: "Cancer treatment, neutron sources.", countries: "Synthetic." },
            { atomicNumber: 99, symbol: "Es", name: "Einsteinium", info: "A synthetic element named after Einstein.", uses: "Scientific research.", countries: "Synthetic." },
            { atomicNumber: 100, symbol: "Fm", name: "Fermium", info: "A synthetic, radioactive element.", uses: "Scientific research.", countries: "Synthetic." },
            { atomicNumber: 101, symbol: "Md", name: "Mendelevium", info: "A synthetic, radioactive element.", uses: "Scientific research.", countries: "Synthetic." },
            { atomicNumber: 102, symbol: "No", name: "Nobelium", info: "A synthetic, radioactive element.", uses: "Scientific research.", countries: "Synthetic." },
            { atomicNumber: 103, symbol: "Lr", name: "Lawrencium", info: "A synthetic, radioactive element.", uses: "Scientific research.", countries: "Synthetic." },
            { atomicNumber: 104, symbol: "Rf", name: "Rutherfordium", info: "A synthetic element with limited uses.", uses: "Scientific research.", countries: "Synthetic." },
            { atomicNumber: 105, symbol: "Db", name: "Dubnium", info: "A synthetic element.", uses: "Scientific research.", countries: "Synthetic." },
            { atomicNumber: 106, symbol: "Sg", name: "Seaborgium", info: "A synthetic element.", uses: "Scientific research.", countries: "Synthetic." },
            { atomicNumber: 107, symbol: "Bh", name: "Bohrium", info: "A synthetic element.", uses: "Scientific research.", countries: "Synthetic." },
            { atomicNumber: 108, symbol: "Hs", name: "Hassium", info: "A synthetic element.", uses: "Scientific research.", countries: "Synthetic." },
            { atomicNumber: 109, symbol: "Mt", name: "Meitnerium", info: "A synthetic element.", uses: "Scientific research.", countries: "Synthetic." },
            { atomicNumber: 110, symbol: "Ds", name: "Darmstadtium", info: "A synthetic element.", uses: "Scientific research.", countries: "Synthetic." },

            { atomicNumber: 111, symbol: "Rg", name: "Roentgenium", info: "A synthetic and highly unstable element.", uses: "Scientific research.", countries: "Synthetic." },
            { atomicNumber: 112, symbol: "Cn", name: "Copernicium", info: "A synthetic element named after Copernicus.", uses: "Scientific research.", countries: "Synthetic." },
            { atomicNumber: 113, symbol: "Nh", name: "Nihonium", info: "A synthetic element named after Japan.", uses: "Scientific research.", countries: "Synthetic." },
            { atomicNumber: 114, symbol: "Fl", name: "Flerovium", info: "A superheavy synthetic element.", uses: "Scientific research.", countries: "Synthetic." },
            { atomicNumber: 115, symbol: "Mc", name: "Moscovium", info: "A synthetic element named after Moscow.", uses: "Scientific research.", countries: "Synthetic." },
            { atomicNumber: 116, symbol: "Lv", name: "Livermorium", info: "A synthetic element named after Lawrence Livermore National Laboratory.", uses: "Scientific research.", countries: "Synthetic." },
            { atomicNumber: 117, symbol: "Ts", name: "Tennessine", info: "A synthetic element named after Tennessee.", uses: "Scientific research.", countries: "Synthetic." },
            { atomicNumber: 118, symbol: "Og", name: "Oganesson", info: "The heaviest synthetic element, named after Yuri Oganessian.", uses: "Scientific research.", countries: "Synthetic." }
];

// Export the elements array for use in other files
export default elements;