[book]
authors = ["mohan-chinnappan-n"]
language = "en"
multilingual = false
src = "src"
title = "Salesforce Development Notes"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"


[output]

[output.html]
additional-css = ["custom.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
mathjax-support = true

