
let editor;const selectionsAvailable=['securityPredicate','leaflet'];async function fetchText(url){const response=await fetch(url);const content=await response.text();return content;}
const urlParams=new URLSearchParams(window.location.search);Split(["#content","#htmlContent"],{sizes:[60,40]});let isFileLoaded=false;let inputExtension="";let originalFileName="";const newTabBtn=document.getElementById('newTab');function setEditorLanguage(extension){const supportedLanguages=monaco.languages.getLanguages();const languageId=supportedLanguages.find((lang)=>lang.extensions?.includes(`.${extension}`));if(languageId){monaco.editor.setModelLanguage(editor.getModel(),languageId.id);}}
require.config({paths:{vs:"https://cdn.jsdelivr.net/npm/monaco-editor@0.27.0/min/vs"},});let initContent=`<html><head><link rel="stylesheet"href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"/></head><body class="container"><h3>Hello Fruits!</h3><ul class="list-group"><li class='list-group-item active'>Jackfruit</li><li class="list-group-item">Mango</li><li class='list-group-item'>Peach</li></ul><h4>Choose</h4><select class='form-control'><option>Jackfruit</option><option>Mango</option><option>Peach</option></select></html>`;if(urlParams.has('c')){await navigator.clipboard.readText().then((clipText)=>{initContent=clipText;});}
var iframe=document.getElementById("output-iframe");const converter=new showdown.Converter({tables:true});function updateIframeContent(editor){const contentType=editor.getModel().getModeId();var htmlContent=editor.getValue();iframe.contentWindow.document.open();if(contentType!=='html')iframe.contentWindow.document.write('<pre>'+htmlContent+'</pre>');else iframe.contentWindow.document.write(htmlContent);iframe.contentWindow.document.close();}
require(["vs/editor/editor.main"],function(){editor=monaco.editor.create(document.getElementById("editor"),{value:initContent,language:"html",theme:"vs-dark",});updateIframeContent(editor);editor.onDidChangeModelContent(function(){var contentType=editor.getModel().getModeId();var isHtml=contentType==="html";iframe.style.display=isHtml?"block":"none";updateIframeContent(editor);});const jsonFileInput=document.getElementById("jsonFileInput");jsonFileInput.addEventListener("change",function(event){var file=event.target.files[0];const fileName=file.name;originalFileName=fileName;inputExtension=fileName.split(".").pop().toLowerCase();setEditorLanguage(inputExtension);if(file){var reader=new FileReader();reader.onload=function(e){var content=e.target.result;if(inputExtension==='md'){editor.setValue(converter.makeHtml(content));}else{editor.setValue(content);}};reader.readAsText(file);}});});function handleFileDrop(e){e.preventDefault();const files=e.dataTransfer.files;if(files.length>0){const file=files[0];const fileName=file.name;originalFileName=fileName;inputExtension=fileName.split(".").pop().toLowerCase();const reader=new FileReader();reader.onload=function(event){const fileContent=event.target.result;if(inputExtension==='md'){editor.setValue(converter.makeHtml(fileContent));}
else{editor.setValue(fileContent);}
isFileLoaded=true;setEditorLanguage(inputExtension);document.getElementById("downloadButton").disabled=false;updateIframeContent(editor);};reader.readAsText(file);}}
function preventDefault(e){e.preventDefault();}
const dropArea=document.getElementById("dropArea");dropArea.addEventListener("dragenter",preventDefault,false);dropArea.addEventListener("dragover",preventDefault,false);dropArea.addEventListener("drop",handleFileDrop,false);function downloadFile(){const fileContent=editor.getValue();const blob=new Blob([fileContent],{type:"text/plain"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=originalFileName;a.style.display="none";document.body.appendChild(a);a.click();document.body.removeChild(a);}
document.getElementById("downloadButton").addEventListener("click",downloadFile);newTabBtn.addEventListener('click',event=>{const newWindow=window.open("","_blank");newWindow.document.write(editor.getValue());newWindow.document.close();});let typeSelected="package";const acConfigMtype={placeHolder:"Search for Sample Docs...",selector:"#autoCompleteMtype",data:{src:selectionsAvailable
},resultItem:{highlight:true,},resultsList:{element:(list,data)=>{const info=document.createElement("p");if(data.results.length){info.innerHTML=`Displaying<strong>${data.results.length}</strong>out of<strong>${data.matches.length}</strong>results`;}else{info.innerHTML=`Found<strong>${data.matches.length}</strong>matching results for<strong>"${data.query}"</strong>`;}
list.prepend(info);},noResults:true,maxResults:15,tabSelect:true,},events:{input:{selection:async(event)=>{const selection=event.detail.selection.value;autoCompleteJSMtype.input.value=selection;await loadData(selection);},},},};const autoCompleteJSMtype=new autoComplete(acConfigMtype);async function loadData(selection){const docUrl=`https:console.log(docUrl);const docData=await fetchText(docUrl);editor.setValue(docData);}
