// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"io/ioutil"
	"unicode/utf8"

	"token"
)

const (
	NoState    = -1
	NumStates  = 67
	NumSymbols = 78
)

type Lexer struct {
	src     []byte
	pos     int
	line    int
	column  int
	Context token.Context
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:     src,
		pos:     0,
		line:    1,
		column:  1,
		Context: nil,
	}
	return lexer
}

// SourceContext is a simple instance of a token.Context which
// contains the name of the source file.
type SourceContext struct {
	Filepath string
}

func (s *SourceContext) Source() string {
	return s.Filepath
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	lexer := NewLexer(src)
	lexer.Context = &SourceContext{Filepath: fpath}
	return lexer, nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = &token.Token{}
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		tok.Pos.Context = l.Context
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	tok.Pos.Context = l.Context

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '"'
1: ' '
2: '!'
3: '?'
4: '"'
5: '0'
6: 'f'
7: 'u'
8: 'n'
9: 'c'
10: 'l'
11: 'e'
12: 't'
13: 'i'
14: 'f'
15: 'e'
16: 'l'
17: 's'
18: 'e'
19: 'r'
20: 'e'
21: 't'
22: 'u'
23: 'r'
24: 'n'
25: 't'
26: 'r'
27: 'u'
28: 'e'
29: 'f'
30: 'a'
31: 'l'
32: 's'
33: 'e'
34: 'a'
35: 'n'
36: 'd'
37: 'o'
38: 'r'
39: '+'
40: '-'
41: '*'
42: '/'
43: '='
44: '='
45: '!'
46: '='
47: '<'
48: '='
49: '<'
50: '>'
51: '='
52: '>'
53: '{'
54: '}'
55: '='
56: '('
57: ')'
58: ','
59: ';'
60: '_'
61: '\t'
62: '\n'
63: '\r'
64: ' '
65: '/'
66: '/'
67: '\n'
68: '/'
69: '*'
70: '*'
71: '*'
72: '/'
73: '1'-'9'
74: 'A'-'Z'
75: 'a'-'z'
76: '0'-'9'
77: .
*/
