"""ggplot-plotnine.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/115k6e8UJ_UQSc1WtCZrT6lTQo523BzOP
"""

from plotnine import ggplot, geom_point, aes, stat_smooth, facet_wrap
from plotnine.data import mtcars

mtcars

( ggplot(mtcars, aes('wt', 'mpg', color='factor(gear)')))

( ggplot(mtcars, aes('wt', 'mpg', color='factor(gear)'))
   + geom_point()


)

( ggplot(mtcars, aes('wt', 'mpg', color='factor(gear)'))
   + geom_point()
   + stat_smooth(method='lm')
)

( ggplot(mtcars, aes('wt', 'mpg', color='factor(gear)'))
   + geom_point()
   + stat_smooth(method='lm')
   + facet_wrap('~gear')
)