// Code generated by gocc; DO NOT EDIT.

package parser

import (
	"github.com/Lebonesco/go-compiler/ast"
)

type (
	ProdTab      [numProductions]ProdTabEntry
	ProdTabEntry struct {
		String     string
		Id         string
		NTType     int
		Index      int
		NumSymbols int
		ReduceFunc func([]Attrib, interface{}) (Attrib, error)
	}
	Attrib interface {
	}
)

var productionsTable = ProdTab{
	ProdTabEntry{
		String: `S' : Program	<<  >>`,
		Id:         "S'",
		NTType:     0,
		Index:      0,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Program : Functions Statements	<< ast.NewProgram(X[0], X[1]) >>`,
		Id:         "Program",
		NTType:     1,
		Index:      1,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewProgram(X[0], X[1])
		},
	},
	ProdTabEntry{
		String: `Functions : Functions Function	<< ast.AppendStatement(X[0], X[1]) >>`,
		Id:         "Functions",
		NTType:     2,
		Index:      2,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.AppendStatement(X[0], X[1])
		},
	},
	ProdTabEntry{
		String: `Functions : empty	<< ast.NewStatementList() >>`,
		Id:         "Functions",
		NTType:     2,
		Index:      3,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewStatementList()
		},
	},
	ProdTabEntry{
		String: `Function : func ident lparen FormalArgs rparen ident StatementBlock	<< ast.NewFunctionStatement(X[1], X[3], X[5], X[6]) >>`,
		Id:         "Function",
		NTType:     3,
		Index:      4,
		NumSymbols: 7,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewFunctionStatement(X[1], X[3], X[5], X[6])
		},
	},
	ProdTabEntry{
		String: `Statements : Statements Statement	<< ast.AppendStatement(X[0], X[1]) >>`,
		Id:         "Statements",
		NTType:     4,
		Index:      5,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.AppendStatement(X[0], X[1])
		},
	},
	ProdTabEntry{
		String: `Statements : empty	<< ast.NewStatementList() >>`,
		Id:         "Statements",
		NTType:     4,
		Index:      6,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewStatementList()
		},
	},
	ProdTabEntry{
		String: `StatementBlock : lbrace Statements rbrace	<< ast.NewBlockStatement(X[1]) >>`,
		Id:         "StatementBlock",
		NTType:     5,
		Index:      7,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewBlockStatement(X[1])
		},
	},
	ProdTabEntry{
		String: `Statement : if Expression StatementBlock IfStatement	<< ast.NewIfStatement(X[1], X[2], X[3]) >>`,
		Id:         "Statement",
		NTType:     6,
		Index:      8,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewIfStatement(X[1], X[2], X[3])
		},
	},
	ProdTabEntry{
		String: `Statement : ident assign Expression semicolon	<< ast.NewAssignStatement(X[0], X[2]) >>`,
		Id:         "Statement",
		NTType:     6,
		Index:      9,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewAssignStatement(X[0], X[2])
		},
	},
	ProdTabEntry{
		String: `Statement : let ident assign Expression semicolon	<< ast.NewIdentInit(X[1], X[3]) >>`,
		Id:         "Statement",
		NTType:     6,
		Index:      10,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewIdentInit(X[1], X[3])
		},
	},
	ProdTabEntry{
		String: `Statement : Expression semicolon	<< ast.NewExpressionStatement(X[0]) >>`,
		Id:         "Statement",
		NTType:     6,
		Index:      11,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewExpressionStatement(X[0])
		},
	},
	ProdTabEntry{
		String: `Statement : return Expression semicolon	<< ast.NewReturnStatement(X[1]) >>`,
		Id:         "Statement",
		NTType:     6,
		Index:      12,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewReturnStatement(X[1])
		},
	},
	ProdTabEntry{
		String: `IfStatement : else StatementBlock	<< X[1], nil >>`,
		Id:         "IfStatement",
		NTType:     7,
		Index:      13,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[1], nil
		},
	},
	ProdTabEntry{
		String: `IfStatement : empty	<<  >>`,
		Id:         "IfStatement",
		NTType:     7,
		Index:      14,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `Expression : Expression Operation Term	<< ast.NewInfixExpression(X[0], X[2], X[1]) >>`,
		Id:         "Expression",
		NTType:     8,
		Index:      15,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewInfixExpression(X[0], X[2], X[1])
		},
	},
	ProdTabEntry{
		String: `Expression : Term	<<  >>`,
		Id:         "Expression",
		NTType:     8,
		Index:      16,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Operation : plus	<<  >>`,
		Id:         "Operation",
		NTType:     9,
		Index:      17,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Operation : minus	<<  >>`,
		Id:         "Operation",
		NTType:     9,
		Index:      18,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Operation : atmost	<<  >>`,
		Id:         "Operation",
		NTType:     9,
		Index:      19,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Operation : atleast	<<  >>`,
		Id:         "Operation",
		NTType:     9,
		Index:      20,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Operation : lt	<<  >>`,
		Id:         "Operation",
		NTType:     9,
		Index:      21,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Operation : gt	<<  >>`,
		Id:         "Operation",
		NTType:     9,
		Index:      22,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Operation : eq	<<  >>`,
		Id:         "Operation",
		NTType:     9,
		Index:      23,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Operation : neq	<<  >>`,
		Id:         "Operation",
		NTType:     9,
		Index:      24,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Operation : and	<<  >>`,
		Id:         "Operation",
		NTType:     9,
		Index:      25,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Operation : or	<<  >>`,
		Id:         "Operation",
		NTType:     9,
		Index:      26,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Term : Term mul Factor	<< ast.NewInfixExpression(X[0], X[2], X[1]) >>`,
		Id:         "Term",
		NTType:     10,
		Index:      27,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewInfixExpression(X[0], X[2], X[1])
		},
	},
	ProdTabEntry{
		String: `Term : Term div Factor	<< ast.NewInfixExpression(X[0], X[2], X[1]) >>`,
		Id:         "Term",
		NTType:     10,
		Index:      28,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewInfixExpression(X[0], X[2], X[1])
		},
	},
	ProdTabEntry{
		String: `Term : string_literal	<< ast.NewStringLiteral(X[0]) >>`,
		Id:         "Term",
		NTType:     10,
		Index:      29,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewStringLiteral(X[0])
		},
	},
	ProdTabEntry{
		String: `Term : Bool	<< ast.NewBoolExpression(X[0]) >>`,
		Id:         "Term",
		NTType:     10,
		Index:      30,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewBoolExpression(X[0])
		},
	},
	ProdTabEntry{
		String: `Term : Factor	<<  >>`,
		Id:         "Term",
		NTType:     10,
		Index:      31,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Factor : lparen Expression rparen	<< X[1], nil >>`,
		Id:         "Factor",
		NTType:     11,
		Index:      32,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[1], nil
		},
	},
	ProdTabEntry{
		String: `Factor : int	<< ast.NewIntegerLiteral(X[0]) >>`,
		Id:         "Factor",
		NTType:     11,
		Index:      33,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewIntegerLiteral(X[0])
		},
	},
	ProdTabEntry{
		String: `Factor : ident	<< ast.NewIdentExpression(X[0]) >>`,
		Id:         "Factor",
		NTType:     11,
		Index:      34,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewIdentExpression(X[0])
		},
	},
	ProdTabEntry{
		String: `Factor : ident lparen Args rparen	<< ast.NewFunctionCall(X[0], X[2]) >>`,
		Id:         "Factor",
		NTType:     11,
		Index:      35,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewFunctionCall(X[0], X[2])
		},
	},
	ProdTabEntry{
		String: `Factor : error	<<  >>`,
		Id:         "Factor",
		NTType:     11,
		Index:      36,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Bool : true	<< true, nil >>`,
		Id:         "Bool",
		NTType:     12,
		Index:      37,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return true, nil
		},
	},
	ProdTabEntry{
		String: `Bool : false	<< false, nil >>`,
		Id:         "Bool",
		NTType:     12,
		Index:      38,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return false, nil
		},
	},
	ProdTabEntry{
		String: `Args : Expression ArgsList	<< ast.AppendArgs(X[0], X[1]) >>`,
		Id:         "Args",
		NTType:     13,
		Index:      39,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.AppendArgs(X[0], X[1])
		},
	},
	ProdTabEntry{
		String: `Args : empty	<<  >>`,
		Id:         "Args",
		NTType:     13,
		Index:      40,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `ArgsList : ArgsList comma Expression	<< ast.AppendArgs(X[2], X[0]) >>`,
		Id:         "ArgsList",
		NTType:     14,
		Index:      41,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.AppendArgs(X[2], X[0])
		},
	},
	ProdTabEntry{
		String: `ArgsList : empty	<< ast.NewArg() >>`,
		Id:         "ArgsList",
		NTType:     14,
		Index:      42,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewArg()
		},
	},
	ProdTabEntry{
		String: `FormalArgs : ident ident FormalArgsList	<< ast.AppendFormalArgs(X[2], X[0], X[1]) >>`,
		Id:         "FormalArgs",
		NTType:     15,
		Index:      43,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.AppendFormalArgs(X[2], X[0], X[1])
		},
	},
	ProdTabEntry{
		String: `FormalArgs : empty	<<  >>`,
		Id:         "FormalArgs",
		NTType:     15,
		Index:      44,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `FormalArgsList : FormalArgsList comma ident ident	<< ast.AppendFormalArgs(X[0], X[2], X[3]) >>`,
		Id:         "FormalArgsList",
		NTType:     16,
		Index:      45,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.AppendFormalArgs(X[0], X[2], X[3])
		},
	},
	ProdTabEntry{
		String: `FormalArgsList : empty	<< ast.NewFormalArg() >>`,
		Id:         "FormalArgsList",
		NTType:     16,
		Index:      46,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewFormalArg()
		},
	},
}
